# Generated by Django 4.2 on 2024-07-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.shutterstock.com/shutterstock/photos/2145440019/display_1500/stock-vector-exciting-new-cafe-bar-restaurant-menu-coming-soon-flat-design-2145440019.jpg', max_length=500),
        ),
    ]
